/*
 * GPIO_cfg.h
 *
 *  Created on: Jul 2, 2024
 *      Author: Mohamed Abdallah Elghzaly
 */

#ifndef GPIO_GPIO_CFG_H_
#define GPIO_GPIO_CFG_H_
#include "GPIO.h"



#define BUTTON1		        ((Button_t){PORTB_PIN7, 0, 0})
#define BUTTON2		        ((Button_t){PORTB_PIN8, 1, 1})
#define BUTTON3		        ((Button_t){PORTB_PIN9, 2, 2})

#define INDUCTION			(PORTB_PIN11)

#define Timer_PWM2			((Timer_PWM_t){100, 0, 0, TIMER3_PWM_EN, PWM_CHANNEL_4_ENABLE | PWM_CHANNEL_3_ENABLE | PWM_CHANNEL_2_ENABLE, EDGE_ALIGNED_MODE})
//#define Timer_PWM2			((Timer_PWM_t){800000, 0, 0, TIMER3_PWM_EN,  PWM_CHANNEL_3_ENABLE , EDGE_ALIGNED_MODE})

#define RGB1_EN				(PORTB_PIN10)
#define RGB2_EN				(PORTA_PIN5)
#define RGB3_EN				(PORTA_PIN6)

#define USART1				((USART_t){115200,USART1_EN, USART_TX_RX, USART_PARITY_NONE, USART_1_STOP_BIT, USART_WORD_LENGTH_8BITS})

#define SHIFT_REG1		 	((ShiftRegister_t){PORTA_PIN1, PORTA_PIN2, PORTA_PIN3})

#define RGB1				((RGBLed_t){Timer_PWM2})












/* port A pins */
#define PORTA_PIN0	  ((Pin_cfg_t){GPIO_OUTPUT_10MHz_GEN_PUSH_PULL, GPIO_PORTA, GPIO_PIN0})
#define PORTA_PIN1	  ((Pin_cfg_t){GPIO_OUTPUT_10MHz_GEN_PUSH_PULL, GPIO_PORTA, GPIO_PIN1})
#define PORTA_PIN2	  ((Pin_cfg_t){GPIO_OUTPUT_10MHz_GEN_PUSH_PULL, GPIO_PORTA, GPIO_PIN2})
#define PORTA_PIN3	  ((Pin_cfg_t){GPIO_OUTPUT_10MHz_GEN_PUSH_PULL, GPIO_PORTA, GPIO_PIN3})
#define PORTA_PIN4	  ((Pin_cfg_t){GPIO_OUTPUT_10MHz_GEN_PUSH_PULL, GPIO_PORTA, GPIO_PIN4})
#define PORTA_PIN5	  ((Pin_cfg_t){GPIO_OUTPUT_10MHz_GEN_PUSH_PULL, GPIO_PORTA, GPIO_PIN5})
#define PORTA_PIN6	  ((Pin_cfg_t){GPIO_OUTPUT_10MHz_GEN_PUSH_PULL, GPIO_PORTA, GPIO_PIN6})
#define PORTA_PIN7	  ((Pin_cfg_t){GPIO_OUTPUT_10MHz_GEN_PUSH_PULL, GPIO_PORTA, GPIO_PIN7})
#define PORTA_PIN8	  ((Pin_cfg_t){GPIO_OUTPUT_10MHz_GEN_PUSH_PULL, GPIO_PORTA, GPIO_PIN8})
#define PORTA_PIN9	  ((Pin_cfg_t){GPIO_OUTPUT_10MHz_GEN_PUSH_PULL, GPIO_PORTA, GPIO_PIN9})
#define PORTA_PIN10	  ((Pin_cfg_t){GPIO_OUTPUT_10MHz_GEN_PUSH_PULL, GPIO_PORTA, GPIO_PIN10})
#define PORTA_PIN11	  ((Pin_cfg_t){GPIO_OUTPUT_10MHz_GEN_PUSH_PULL, GPIO_PORTA, GPIO_PIN11})
#define PORTA_PIN12	  ((Pin_cfg_t){GPIO_OUTPUT_10MHz_GEN_PUSH_PULL, GPIO_PORTA, GPIO_PIN12})
#define PORTA_PIN13	  ((Pin_cfg_t){GPIO_OUTPUT_10MHz_GEN_PUSH_PULL, GPIO_PORTA, GPIO_PIN13})
#define PORTA_PIN14	  ((Pin_cfg_t){GPIO_OUTPUT_10MHz_GEN_PUSH_PULL, GPIO_PORTA, GPIO_PIN14})
#define PORTA_PIN15	  ((Pin_cfg_t){GPIO_OUTPUT_10MHz_GEN_PUSH_PULL, GPIO_PORTA, GPIO_PIN15})

/* port B pins */
#define PORTB_PIN0	  ((Pin_cfg_t){GPIO_OUTPUT_10MHz_GEN_PUSH_PULL, GPIO_PORTB, GPIO_PIN0})
#define PORTB_PIN1	  ((Pin_cfg_t){GPIO_OUTPUT_10MHz_GEN_PUSH_PULL, GPIO_PORTB, GPIO_PIN1})
#define PORTB_PIN2	  ((Pin_cfg_t){GPIO_OUTPUT_10MHz_GEN_PUSH_PULL, GPIO_PORTB, GPIO_PIN2})
#define PORTB_PIN3	  ((Pin_cfg_t){GPIO_OUTPUT_10MHz_GEN_PUSH_PULL, GPIO_PORTB, GPIO_PIN3})
#define PORTB_PIN4	  ((Pin_cfg_t){GPIO_OUTPUT_10MHz_GEN_PUSH_PULL, GPIO_PORTB, GPIO_PIN4})
#define PORTB_PIN5	  ((Pin_cfg_t){GPIO_OUTPUT_10MHz_GEN_PUSH_PULL, GPIO_PORTB, GPIO_PIN5})
#define PORTB_PIN6	  ((Pin_cfg_t){GPIO_OUTPUT_10MHz_GEN_PUSH_PULL, GPIO_PORTB, GPIO_PIN6})
#define PORTB_PIN7	  ((Pin_cfg_t){GPIO_INPUT_PULL_DOWN_MODE, GPIO_PORTB, GPIO_PIN7})
#define PORTB_PIN8	  ((Pin_cfg_t){GPIO_INPUT_PULL_DOWN_MODE, GPIO_PORTB, GPIO_PIN8})
#define PORTB_PIN9	  ((Pin_cfg_t){GPIO_INPUT_PULL_DOWN_MODE, GPIO_PORTB, GPIO_PIN9})
#define PORTB_PIN10	  ((Pin_cfg_t){GPIO_OUTPUT_10MHz_GEN_PUSH_PULL, GPIO_PORTB, GPIO_PIN10})
#define PORTB_PIN11	  ((Pin_cfg_t){GPIO_OUTPUT_50MHz_GEN_PUSH_PULL, GPIO_PORTB, GPIO_PIN11})
#define PORTB_PIN12	  ((Pin_cfg_t){GPIO_OUTPUT_10MHz_GEN_PUSH_PULL, GPIO_PORTB, GPIO_PIN12})
#define PORTB_PIN13	  ((Pin_cfg_t){GPIO_OUTPUT_10MHz_GEN_PUSH_PULL, GPIO_PORTB, GPIO_PIN13})
#define PORTB_PIN14	  ((Pin_cfg_t){GPIO_OUTPUT_10MHz_GEN_PUSH_PULL, GPIO_PORTB, GPIO_PIN14})
#define PORTB_PIN15	  ((Pin_cfg_t){GPIO_OUTPUT_10MHz_GEN_PUSH_PULL, GPIO_PORTB, GPIO_PIN15})

/* port C pins */
#define PORTC_PIN0	  ((Pin_cfg_t){GPIO_OUTPUT_2MHz_GEN_PUSH_PULL, GPIO_PORTC, GPIO_PIN0})
#define PORTC_PIN1	  ((Pin_cfg_t){GPIO_OUTPUT_2MHz_GEN_PUSH_PULL, GPIO_PORTC, GPIO_PIN1})
#define PORTC_PIN2	  ((Pin_cfg_t){GPIO_OUTPUT_2MHz_GEN_PUSH_PULL, GPIO_PORTC, GPIO_PIN2})
#define PORTC_PIN3	  ((Pin_cfg_t){GPIO_OUTPUT_2MHz_GEN_PUSH_PULL, GPIO_PORTC, GPIO_PIN3})
#define PORTC_PIN4	  ((Pin_cfg_t){GPIO_OUTPUT_2MHz_GEN_PUSH_PULL, GPIO_PORTC, GPIO_PIN4})
#define PORTC_PIN5	  ((Pin_cfg_t){GPIO_OUTPUT_2MHz_GEN_PUSH_PULL, GPIO_PORTC, GPIO_PIN5})
#define PORTC_PIN6	  ((Pin_cfg_t){GPIO_OUTPUT_2MHz_GEN_PUSH_PULL, GPIO_PORTC, GPIO_PIN6})
#define PORTC_PIN7	  ((Pin_cfg_t){GPIO_OUTPUT_2MHz_GEN_PUSH_PULL, GPIO_PORTC, GPIO_PIN7})
#define PORTC_PIN8	  ((Pin_cfg_t){GPIO_OUTPUT_2MHz_GEN_PUSH_PULL, GPIO_PORTC, GPIO_PIN8})
#define PORTC_PIN9	  ((Pin_cfg_t){GPIO_OUTPUT_2MHz_GEN_PUSH_PULL, GPIO_PORTC, GPIO_PIN9})
#define PORTC_PIN10	  ((Pin_cfg_t){GPIO_OUTPUT_2MHz_GEN_PUSH_PULL, GPIO_PORTC, GPIO_PIN10})
#define PORTC_PIN11	  ((Pin_cfg_t){GPIO_OUTPUT_2MHz_GEN_PUSH_PULL, GPIO_PORTC, GPIO_PIN11})
#define PORTC_PIN12	  ((Pin_cfg_t){GPIO_OUTPUT_2MHz_GEN_PUSH_PULL, GPIO_PORTC, GPIO_PIN12})
#define PORTC_PIN13	  ((Pin_cfg_t){GPIO_OUTPUT_2MHz_GEN_PUSH_PULL, GPIO_PORTC, GPIO_PIN13})
#define PORTC_PIN14	  ((Pin_cfg_t){GPIO_OUTPUT_2MHz_GEN_PUSH_PULL, GPIO_PORTC, GPIO_PIN14})
#define PORTC_PIN15	  ((Pin_cfg_t){GPIO_OUTPUT_2MHz_GEN_PUSH_PULL, GPIO_PORTC, GPIO_PIN15})

/* port D pins */
#define PORTD_PIN0	  ((Pin_cfg_t){GPIO_OUTPUT_2MHz_GEN_PUSH_PULL, GPIO_PORTD, GPIO_PIN0})
#define PORTD_PIN1	  ((Pin_cfg_t){GPIO_OUTPUT_2MHz_GEN_PUSH_PULL, GPIO_PORTD, GPIO_PIN1})
#define PORTD_PIN2	  ((Pin_cfg_t){GPIO_OUTPUT_2MHz_GEN_PUSH_PULL, GPIO_PORTD, GPIO_PIN2})
#define PORTD_PIN3	  ((Pin_cfg_t){GPIO_OUTPUT_2MHz_GEN_PUSH_PULL, GPIO_PORTD, GPIO_PIN3})
#define PORTD_PIN4	  ((Pin_cfg_t){GPIO_OUTPUT_2MHz_GEN_PUSH_PULL, GPIO_PORTD, GPIO_PIN4})
#define PORTD_PIN5	  ((Pin_cfg_t){GPIO_OUTPUT_2MHz_GEN_PUSH_PULL, GPIO_PORTD, GPIO_PIN5})
#define PORTD_PIN6	  ((Pin_cfg_t){GPIO_OUTPUT_2MHz_GEN_PUSH_PULL, GPIO_PORTD, GPIO_PIN6})
#define PORTD_PIN7	  ((Pin_cfg_t){GPIO_OUTPUT_2MHz_GEN_PUSH_PULL, GPIO_PORTD, GPIO_PIN7})
#define PORTD_PIN8	  ((Pin_cfg_t){GPIO_OUTPUT_2MHz_GEN_PUSH_PULL, GPIO_PORTD, GPIO_PIN8})
#define PORTD_PIN9	  ((Pin_cfg_t){GPIO_OUTPUT_2MHz_GEN_PUSH_PULL, GPIO_PORTD, GPIO_PIN9})
#define PORTD_PIN10	  ((Pin_cfg_t){GPIO_OUTPUT_2MHz_GEN_PUSH_PULL, GPIO_PORTD, GPIO_PIN10})
#define PORTD_PIN11	  ((Pin_cfg_t){GPIO_OUTPUT_2MHz_GEN_PUSH_PULL, GPIO_PORTD, GPIO_PIN11})
#define PORTD_PIN12	  ((Pin_cfg_t){GPIO_OUTPUT_2MHz_GEN_PUSH_PULL, GPIO_PORTD, GPIO_PIN12})
#define PORTD_PIN13	  ((Pin_cfg_t){GPIO_OUTPUT_2MHz_GEN_PUSH_PULL, GPIO_PORTD, GPIO_PIN13})
#define PORTD_PIN14	  ((Pin_cfg_t){GPIO_OUTPUT_2MHz_GEN_PUSH_PULL, GPIO_PORTD, GPIO_PIN14})
#define PORTD_PIN15	  ((Pin_cfg_t){GPIO_OUTPUT_2MHz_GEN_PUSH_PULL, GPIO_PORTD, GPIO_PIN15})

/* port E pins */
#define PORTE_PIN0	  ((Pin_cfg_t){GPIO_OUTPUT_2MHz_GEN_PUSH_PULL, GPIO_PORTE, GPIO_PIN0})
#define PORTE_PIN1	  ((Pin_cfg_t){GPIO_OUTPUT_2MHz_GEN_PUSH_PULL, GPIO_PORTE, GPIO_PIN1})
#define PORTE_PIN2	  ((Pin_cfg_t){GPIO_OUTPUT_2MHz_GEN_PUSH_PULL, GPIO_PORTE, GPIO_PIN2})
#define PORTE_PIN3	  ((Pin_cfg_t){GPIO_OUTPUT_2MHz_GEN_PUSH_PULL, GPIO_PORTE, GPIO_PIN3})
#define PORTE_PIN4	  ((Pin_cfg_t){GPIO_OUTPUT_2MHz_GEN_PUSH_PULL, GPIO_PORTE, GPIO_PIN4})
#define PORTE_PIN5	  ((Pin_cfg_t){GPIO_OUTPUT_2MHz_GEN_PUSH_PULL, GPIO_PORTE, GPIO_PIN5})
#define PORTE_PIN6	  ((Pin_cfg_t){GPIO_OUTPUT_2MHz_GEN_PUSH_PULL, GPIO_PORTE, GPIO_PIN6})
#define PORTE_PIN7	  ((Pin_cfg_t){GPIO_OUTPUT_2MHz_GEN_PUSH_PULL, GPIO_PORTE, GPIO_PIN7})
#define PORTE_PIN8	  ((Pin_cfg_t){GPIO_OUTPUT_2MHz_GEN_PUSH_PULL, GPIO_PORTE, GPIO_PIN8})
#define PORTE_PIN9	  ((Pin_cfg_t){GPIO_OUTPUT_2MHz_GEN_PUSH_PULL, GPIO_PORTE, GPIO_PIN9})
#define PORTE_PIN10	  ((Pin_cfg_t){GPIO_OUTPUT_2MHz_GEN_PUSH_PULL, GPIO_PORTE, GPIO_PIN10})
#define PORTE_PIN11	  ((Pin_cfg_t){GPIO_OUTPUT_2MHz_GEN_PUSH_PULL, GPIO_PORTE, GPIO_PIN11})
#define PORTE_PIN12	  ((Pin_cfg_t){GPIO_OUTPUT_2MHz_GEN_PUSH_PULL, GPIO_PORTE, GPIO_PIN12})
#define PORTE_PIN13	  ((Pin_cfg_t){GPIO_OUTPUT_2MHz_GEN_PUSH_PULL, GPIO_PORTE, GPIO_PIN13})
#define PORTE_PIN14	  ((Pin_cfg_t){GPIO_OUTPUT_2MHz_GEN_PUSH_PULL, GPIO_PORTE, GPIO_PIN14})
#define PORTE_PIN15	  ((Pin_cfg_t){GPIO_OUTPUT_2MHz_GEN_PUSH_PULL, GPIO_PORTE, GPIO_PIN15})


#endif /* GPIO_GPIO_CFG_H_ */
